#!/bin/bash
# 7-highlander

# Trap SIGTERM and respond with a custom message
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
